// Automatically generated by Packet Go code generator.
package meta

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"net"

	"github.com/packet/packet/src/go/packet"

	"github.com/soheilhy/beehive-netctrl/net/ethernet"
	"github.com/soheilhy/beehive-netctrl/net/lldp"
)
